# permissions for end users to edit arithmetics.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: arithmetic-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: math-operator
    app.kubernetes.io/part-of: math-operator
    app.kubernetes.io/managed-by: kustomize
  name: arithmetic-editor-role
rules:
- apiGroups:
  - math.stream.com
  resources:
  - arithmetics
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - math.stream.com
  resources:
  - arithmetics/status
  verbs:
  - get
