---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - math.stream.com
  resources:
  - arithmetics
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - math.stream.com
  resources:
  - arithmetics/finalizers
  verbs:
  - update
- apiGroups:
  - math.stream.com
  resources:
  - arithmetics/status
  verbs:
  - get
  - patch
  - update
